apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-view
  labels:
    app: street-view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: street-view
  template:
    metadata:
      labels:
        app: street-view
    spec:
      containers:
        - name: street-view
          image: sujiththirumalaisamy/street-food:083e2c8af5c4a3035d44d26fb0bc935ed9f26dde
          imagePullPolicy: Always
          volumeMounts:
            - name: secret
              mountPath: /usr/src/app/.env
              subPath: .env
          ports:
            - containerPort: 3000
      volumes:
        - name: secret
          secret:
            secretName: street-view-secrets
            items:
              - key: .env
                path: .env
