apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-view
  labels:
    app: street-view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: street-view
  template:
    metadata:
      labels:
        app: street-view
    spec:
      containers:
        - name: street-view
          image: sujiththirumalaisamy/street-food:3d4fcad2e7a6e5b76e1ea451b2e442f984bf6661
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: street-view-secrets
                  key: DATABASE_URL
          ports:
            - containerPort: 3000
