apiVersion: v1
kind: Service
metadata:
  name: street-view-svc
spec:
  selector:
    app: street-view
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: street-view-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - street-view.isujith.dev
      secretName: street-view-tls
  rules:
    - host: street-view.isujith.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: street-view-svc
                port:
                  number: 80
