apiVersion: v1
kind: Service
metadata:
  name: rahul-next-svc
spec:
  selector:
    app: rahul-next
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rahul-next-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - omara.isujith.dev
    secretName: omara-rahul-dev-tls
  rules:
  - host: omara.isujith.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rahul-next-svc
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rahul-node-svc 
spec:
  selector:
    app: rahul-node
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rahul-node-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - api-omara.isujith.dev
    secretName: api-omara-rahul-dev-tls
  rules:
  - host: api-omara.isujith.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rahul-node-svc
            port:
              number: 80
