apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest
  labels:
    app: contest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest
  template:
    metadata:
      labels:
        app: contest-api
    spec:
      containers:
        - name: contest
          image: sujiththirumalaisamy/contest-api:057b620becabdcd1b4245c22b843d06639b44aab
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
