apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest
  labels:
    app: contest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest
  template:
    metadata:
      labels:
        app: contest
    spec:
      containers:
        - name: contest
          image: sujiththirumalaisamy/contest-api:05c8af8367b0b0cfd833643e76a077b85fc7da14
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
