apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest
  labels:
    app: contest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest
  template:
    metadata:
      labels:
        app: contest
    spec:
      containers:
        - name: contest
          image: sujiththirumalaisamy/contest-api:96827de665b40bcc28a4e71e74e2673fb61e23ab
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
