apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-me
  labels:
    app: cv-me
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  selector:
    matchLabels:
      app: cv-me
  template:
    metadata:
      labels:
        app: cv-me
    spec:
      containers:
        - name: cv-me
          image: sujiththirumalaisamy/cv:99e2ba207ab2b8856d13496f8e6b6a8ed6fb74df
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 7
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 7
            periodSeconds: 5
