apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-me
  labels:
    app: cv-me
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  selector:
    matchLabels:
      app: cv-me
  template:
    metadata:
      labels:
        app: cv-me
    spec:
      containers:
        - name: cv-me
          image: sujiththirumalaisamy/cv:fe06958e30946d21d1ba4708e642bb64b5c0925a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 7
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 7
            periodSeconds: 5
