apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cv-route
  namespace: default

spec:
  parentRefs:
  - name: gateway-api
    sectionName: http
    kind: Gateway
  - name: gateway-api
    sectionName: https
    kind: Gateway

  hostnames:
  - cv.isujith.dev
  - isujith.dev

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: cv-service
      port: 80
      weight: 1
