apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - isujith.dev
      secretName: root-cert
  rules:
    - host: isujith.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-service
                port:
                  number: 80
