apiVersion: v1
kind: Service
metadata:
  name: vs-be-service
spec:
  selector:
    app: vs-be
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vs-be-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - vs-be.isujith.dev
      secretName: vs-be-cert
  rules:
    - host: vs-be.isujith.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vs-be-service
                port:
                  number: 80
