apiVersion: v1
kind: Service
metadata:
  name: vs-be-service
spec:
  selector:
    app: vs-be
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vs-be-route
  namespace: default

spec:
  parentRefs:
  - name: gateway-api
    sectionName: http
    kind: Gateway
  - name: gateway-api
    sectionName: https
    kind: Gateway

  hostnames:
  - vs-be.isujith.dev

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: vs-be-service
      port: 80
      weight: 1
