apiVersion: v1
kind: Secret
metadata:
  name: sports-hub-backend-secret
type: Opaque
data:
  .env: QVVUSF9LRVk9WkkwUDU3R1luOVFEMHdRZ1VhYmFGUjg5UnpTa3NBZ3YKTU9OR09fREJfS0VZPXN1aml0aDpUbHRxeWpLOWZibGYzWDBGQHRlYW10YW1pemhhbi5rYmduZ3VsLm1vbmdvZGIubmV0L3Nwb3J0LWh1Yj9yZXRyeVdyaXRlcz10cnVlCkZJUkVCQVNFX1NUT1JBR0VfQlVDS0VUX0lEPWl0YW1pemhhbi5hcHBzcG90LmNvbQpGSVJFQkFTRV9BUElfS0VZPUFJemFTeUJyMmlrNEg1MGRYU0pMRi0wRTVWeTV4VXFvTDRvUV96dwpGSVJFQkFTRV9ET01BSU49aXRhbWl6aGFuCkZJUkVCQVNFX0RBVEFCQVNFX1VSTD1odHRwczovL2l0YW1pemhhbi1kZWZhdWx0LXJ0ZGIuZmlyZWJhc2Vpby5jb20KRklSRUJBU0VfUFJPSkVDVF9JRD1pdGFtaXpoYW4K
