apiVersion: v1
kind: Service
metadata:
  name: sports-hub-frontend-service
spec:
  selector:
    app: sports-hub-frontend
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sports-hub-frontend-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - kk-sdat.itamizhan.com
      secretName: sports-hub-frontend-cert
  rules:
    - host: kk-sdat.itamizhan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sports-hub-frontend-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sports-hub-backend-service
spec:
  selector:
    app: sports-hub-backend
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sports-hub-backend-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - api-kk-sdat.itamizhan.com
      secretName: sports-hub-backend-cert
  rules:
    - host: api-kk-sdat.itamizhan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sports-hub-backend-service
                port:
                  number: 80
